- name: use the k8s cluster master role
  hosts: localhost
  become: yes
  roles:
    - ansible_kubernetes_master_role 

- name: use the k8s cluster worker role
  hosts: 20.231.229.168
  become: yes
  roles:
    - ansible_kubernetes_worker_role 
